### ISSUE TITLE
"BUG: Missing Headers" Error Not Triggering Callbacks in Asynchronous Requests

### ISSUE THREAD

**Issue by KarimAziev** [magit/ghub#166] opened 2024-03-20 08:51 UTC
**Expected Behavior**:
I expected ghub to execute the `:errorback` handler or the callback during errors, notably for the error "error in process filter: BUG: missing headers; but there’s a patch for that."

**Observed Behavior**:
Even with the most recent versions of Emacs and ghub, the error "error in process filter: BUG: missing headers; but there’s a patch for that" sporadically occurs in my packages ([igist](https://github.com/KarimAziev/igist), [gh-repo](https://github.com/KarimAziev/gh-repo), [github-code-search](https://github.com/KarimAziev/github-code-search)) and has persisted for at least two years. This issue is not confined to interactions through specific packages.

Identifying the exact cause is difficult, though it seems related to keyboard interruptions. The main issue is that when this error arises during any asynchronous request, ghub does not execute either the `:errorback` handler or the callback, preventing any form of error handling or cleanup.

**Steps to Reproduce**:
1. Use the latest versions of Emacs and ghub.
2. The issue can manifest during any asynchronous ghub request, not just those initiated through specific packages like igist or gh-repo. To reproduce, evaluate the following in Emacs:

```elisp
(defun ghub--handle-response-headers (_status req)
  (goto-char (point-min))
  (forward-line 1)
  (let (headers)
    (when ;; temporarily overriding this condition to true
        t
      (setq url-debug t)
      (error "BUG: missing headers; but there's a patch for that see https://github.com/magit/ghub/wiki/Known-Issues"))
    (while (re-search-forward "^\\([^:]*\\): \\(.+\\)"
                              url-http-end-of-headers t)
      (push (cons (match-string 1)
                  (match-string 2))
            headers))
    (setq headers (nreverse headers))
    (goto-char (1+ url-http-end-of-headers))
    (if (and req (or (ghub--req-callback req)
                     (ghub--req-errorback req)))
        (setq-local ghub-response-headers headers)
      (setq-default ghub-response-headers headers))
    headers))

(ghub-request "GET" "/gists/public" nil
                                 :auth 'none
                                 :host "api.github.com"
                                 :forge 'github
                                 :errorback
                                 (lambda (&rest _args)
                                   ;; Expected to execute but does not
                                   (message "ERRORBACK executed"))
                                 :callback
                                 (lambda (&rest _)
                                   ;; Expected to execute but does not
                                   (message "CALLBACK executed")))
```

**Comment by KarimAziev** [comment] 2024-03-20 13:26
Hello

**Comment by tarsius** [comment] 2024-03-20 14:43
This defect is considered a BUG not an error, that's why it is not handled as an error. It is unknown where the bug lies. It *may* turn out to be a defect/error on the server side, in which case we should treat it as an error. I do however suspect that it is a bug in `url.el`. It may also be a bug in `ghub.el`, but I think that's least likely.

The problem is that we get a completely empty response. Actually I don't think that we *received* a completely empty response, without headers or anything. Instead I think that `url.el` presents an empty buffer to the caller due to some bug. This bug *may* be triggered by some error, that `url.el` fails to handle, but that failure would be a bug in `url.el`.

I would greatly appreciative any help finally figuring this out, but think invoking the errorback would make that *harder*. This is a bug at a low level and should be investigated using a debugger and/or debug statements.

**Comment by KarimAziev** [comment] 2024-03-20 18:03
From the backtrace, we can see that when a connection failure occurs (e.g., the failure to connect to `api.github.com`), `url.el` appropriately calls `ghub--handle-response` with an error status (e.g., `(:error (error connection-failed "connect" :host "api.github.com" :service 443))`).

However, due to the immediate triggering of an error within `ghub--handle-response-headers` without checking the status argument at all, the current scenario precludes the execution of any designated `errorback` function.

I am not sure, but in the case of a `connection-failed` error, it is expected that you might not receive any HTTP headers, as well as potentially observe an empty buffer.

The suggestion here is to revise `ghub--handle-response-headers` to either:

- Not raise an immediate error for missing headers when an error status is present, thus allowing the errorback handling to proceed.
- Introduce an early error handling checkpoint that could invoke the `errorback` before proceeding with header checks.

**Comment by tarsius** [comment] 2024-03-20 19:02
It sounds like Ghub indeed has to be adjusted to handle the case when the connection fails completely (as opposed to the server telling us that something is wrong).

I'm rather busy, so it might take a while until I get to that.

**Comment by tarsius** [comment] 2024-08-20 18:54
I pushed something to the `timeout` branch, please give it a try.

**Comment by tarsius** [comment] 2024-08-21 14:51
I've merged into the `main` branch.  Please let me know if you run into any problems.

**Closed** 2024-08-21 14:52 UTC

**Comment by KarimAziev** [comment] 2024-08-21 15:24
Thank you, it seems to work correctly.

**Comment by anquegi** [comment] 2024-09-17 05:17
I get something similar, hope next update in doom emacs get this changes:

Pulling TelefonicaTC2Tech/antifraud...
Decrypting /home/toni/.authinfo.gpg...done
Using a proxy for https...
error in process sentinel: ghub--handle-response-headers: Ghub: BUG: No headers in response buffer: #<buffer  *http api.github.com:443*>
error in process sentinel: Ghub: BUG: No headers in response buffer: #<buffer  *http api.github.com:443*> [3 times]
